# Tables

[payload]
    [[payload.login]]
        username = "test+++"
        password = "Test123;"
        csrfmiddlewaretoken = ""
    [[payload.weight]]
        date = '1998-5-5'
        weight = 77
        csrfmiddlewaretoken = ""
    [[payload.plan]]
        description = "Tragi tare te faci mare nu conteaza cate clase cat timp tu poti sa rupi oase"
        goal = "false"
        [[payload.plan.meal]]
            plan = 61273
            [[payload.plan.meal.item]]
                meal = 153284
                amount = 5
                ingredient = 5655
    [[payload.exercise]]
        description = "Pentru brate mari si tari Sa dai in cap la dusmani Sa nu ai mila de niciunu Sa lovesti mai rau ca tunu"
        name = "Bomba"
        category = 9
        language = 2
    [[payload.workout]]
        creation_date = '2001-11-4'
        [[payload.workout.day]]
            description = "Odihna"
            training = 229245
            day = [3,2]
            [[payload.workout.day.sets]]
                exerciseday = 116468
                exercises = [13,14,15,16]
                sets = 1
    [[payload.schedule]]
        name = "Summer Goals"
        start_date = "2020-04-06"
        [[payload.schedule.link]]
            schedule = 148139
            workout = 229245
