# Tables

[payload]
    [[payload.login]]
        username = "test+++"
        password = "Test123;"
        csrfmiddlewaretoken = ""
    [[payload.weight]]
        date = '2005-5-5'
        weight = 71
        csrfmiddlewaretoken = ""
    [[payload.plan]]
        description = "Tragi tare te faci mare nu conteaza cate clase cat timp tu poti sa rupi oase"
        goal = false
    [[payload.meal]]
        plan = ""
    [[payload.item]]
        meal = ""
        amount = 5
        ingredient = 5555
    [[payload.exercise]]
        description = "Pentru brate mari si tari Sa dai in cap la dusmani Sa nu ai mila de niciunu Sa lovesti mai rau ca tunu"
        name = "Bomba"
        category = 9
        language = 2
    [[payload.workout]]
        creation_date = '2001-11-4'
    [[payload.day]]
        description = "Odihna"
        training = ""
        day = 3
    [[payload.day]]
        description = "Odihna"
        training = ""
        day = 4
    [[payload.sets]]
        exerciseday = ""
        exercises = 11
        sets = 1
    [[payload.schedule]]
        name = "Summer Goals"
        start_date = "2020-04-06"
    [[payload.link]]
        schedule = ""
        workout = ""
