# Tables

[payload]
    [[payload.login]]
        username = "test+++"
        password = "Test123;"
        csrfmiddlewaretoken = ""
    [[payload.workout]]
        creation_date = '2001-11-4'
        comment = "bineee"
        [[payload.workout.day]]
            description = "Odihna"
            training = 231581
            day = [3,2]

