# Tables

[payload]
    [[payload.login]]
        username = "test+++"
        password = "Test123;"
        csrfmiddlewaretoken = ""
    [[payload.weight]]
        date = '1998-5-5'
        weight = 77
        csrfmiddlewaretoken = ""
    [[payload.plan]]
        [[payload.plan.meal]]
            [[payload.plan.meal.item]]
                meal = 153417
                amount = 5
                ingredient = 5655