# Tables

[payload]
    [[payload.login]]
        username = "test+++"
        password = "Test123;"
        csrfmiddlewaretoken = ""
    [[payload.weight]]
        date = '1998-5-5'
        weight = 77
        csrfmiddlewaretoken = ""
    [[payload.plan]]
        [[payload.plan.meal]]
            plan = 61340