# Tables

[payload]
    [[payload.login]]
        username = "test+++"
        password = "Test123;"
        csrfmiddlewaretoken = ""
    [[payload.plan]]
        description = "Tragi tare te faci mare nu conteaza cate clase cat timp tu poti sa rupi oase"
        goal = "false"